language: cpp

install:
  - python3 -m pip install --upgrade pip setuptools
  # Install  CMake >= 3.15
  - python3 -m pip install cmake


jobs:
  include:
    - os: osx
      compiler: gcc
      osx_image: xcode11.2    # includes gcc-9 by default
      env:
        - GCC_VER="9"
        - MATRIX_EVAL="CC=gcc-${GCC_VER} && CXX=g++-${GCC_VER}"
    - os: osx
      compiler: clang
      osx_image: xcode11.2
      env:
        - MATRIX_EVAL=""
    - os: linux
      dist: bionic
      compiler: gcc
      env:
        - GCC_VER="9"
        - MATRIX_EVAL="CC=gcc-${GCC_VER} && CXX=g++-${GCC_VER}"

      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            # I couldn't get ${GCC_VER} in here successfully
            - gcc-9
            - g++-9
            - doxygen
            - python3-pip
      after_script:
        - bash <(curl -s https://codecov.io/bash) -x /usr/bin/gcov-${GCC_VER}
    - os: linux
      dist: bionic
      compiler: clang
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
      addons: { apt: { packages: ['doxygen', 'python3-pip'] } }


before_script:
  - eval "${MATRIX_EVAL}"

script:
  - cmake -S . -B ./build  ../
  - cmake --build ./build
  - cd build && ctest
